<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <IsAotCompatible>true</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\UTM.Core\UTM.Core.csproj" />
    <ProjectReference Include="..\UTM.Monitoring\UTM.Monitoring.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Numerics.Tensors" Version="8.0.0" />
  </ItemGroup>

</Project>
